src/java/control/ReservacionController.java
package control;

import entidad.Reservacion;
import control.util.JsfUtil;
import control.util.JsfUtil.PersistAction;
import sesion.ReservacionFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("reservacionController")
@SessionScoped
public class ReservacionController implements Serializable {

    @EJB
    private sesion.ReservacionFacade ejbFacade;
    private List<Reservacion> items = null;
    private Reservacion selected;

    public ReservacionController() {
    }

    public Reservacion getSelected() {
        return selected;
    }

    public void setSelected(Reservacion selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private ReservacionFacade getFacade() {
        return ejbFacade;
    }

    public Reservacion prepareCreate() {
        selected = new Reservacion();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("ReservacionCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("ReservacionUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("ReservacionDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Reservacion> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Reservacion getReservacion(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Reservacion> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Reservacion> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Reservacion.class)
    public static class ReservacionControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ReservacionController controller = (ReservacionController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "reservacionController");
            return controller.getReservacion(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Reservacion) {
                Reservacion o = (Reservacion) object;
                return getStringKey(o.getIdReservacion());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Reservacion.class.getName()});
                return null;
            }
        }

    }

}

web/reservacion/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ReservacionCreateDlg" widgetVar="ReservacionCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateReservacionTitle}">
            <h:form id="ReservacionCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{reservacionController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateReservacionLabel_idReservacion}" for="idReservacion" />
                        <p:inputText id="idReservacion" value="#{reservacionController.selected.idReservacion}" title="#{bundle.CreateReservacionTitle_idReservacion}" required="true" requiredMessage="#{bundle.CreateReservacionRequiredMessage_idReservacion}"/>
                        <p:outputLabel value="#{bundle.CreateReservacionLabel_fechaReservacion}" for="fechaReservacion" />
                        <p:calendar id="fechaReservacion" pattern="MM/dd/yyyy" value="#{reservacionController.selected.fechaReservacion}" title="#{bundle.EditReservacionTitle_fechaReservacion}" required="true" requiredMessage="#{bundle.EditReservacionRequiredMessage_fechaReservacion}" showOn="button"/>
                        <p:outputLabel value="#{bundle.CreateReservacionLabel_fechaRecogerLibros}" for="fechaRecogerLibros" />
                        <p:calendar id="fechaRecogerLibros" pattern="MM/dd/yyyy" value="#{reservacionController.selected.fechaRecogerLibros}" title="#{bundle.EditReservacionTitle_fechaRecogerLibros}" required="true" requiredMessage="#{bundle.EditReservacionRequiredMessage_fechaRecogerLibros}" showOn="button"/>
                        <p:outputLabel value="#{bundle.CreateReservacionLabel_idUsuario}" for="idUsuario" />
                        <p:selectOneMenu id="idUsuario" value="#{reservacionController.selected.idUsuario}" required="true" requiredMessage="#{bundle.EditReservacionRequiredMessage_idUsuario}">
                            <f:selectItems value="#{usuarioController.itemsAvailableSelectOne}"
                                           var="idUsuarioItem"
                                           itemValue="#{idUsuarioItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{reservacionController.create}" value="#{bundle.Save}" update="display,:ReservacionListForm:datalist,:growl" oncomplete="handleSubmit(args,'ReservacionCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ReservacionCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/reservacion/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ReservacionEditDlg" widgetVar="ReservacionEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditReservacionTitle}">
            <h:form id="ReservacionEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{reservacionController.selected != null}">
                        <p:outputLabel value="#{bundle.EditReservacionLabel_idReservacion}" for="idReservacion" />
                        <p:inputText id="idReservacion" value="#{reservacionController.selected.idReservacion}" title="#{bundle.EditReservacionTitle_idReservacion}" required="true" requiredMessage="#{bundle.EditReservacionRequiredMessage_idReservacion}"/>
                        <p:outputLabel value="#{bundle.EditReservacionLabel_fechaReservacion}" for="fechaReservacion" />
                        <p:calendar id="fechaReservacion" pattern="MM/dd/yyyy" value="#{reservacionController.selected.fechaReservacion}" title="#{bundle.EditReservacionTitle_fechaReservacion}" required="true" requiredMessage="#{bundle.EditReservacionRequiredMessage_fechaReservacion}" showOn="button"/>
                        <p:outputLabel value="#{bundle.EditReservacionLabel_fechaRecogerLibros}" for="fechaRecogerLibros" />
                        <p:calendar id="fechaRecogerLibros" pattern="MM/dd/yyyy" value="#{reservacionController.selected.fechaRecogerLibros}" title="#{bundle.EditReservacionTitle_fechaRecogerLibros}" required="true" requiredMessage="#{bundle.EditReservacionRequiredMessage_fechaRecogerLibros}" showOn="button"/>
                        <p:outputLabel value="#{bundle.EditReservacionLabel_idUsuario}" for="idUsuario" />
                        <p:selectOneMenu id="idUsuario" value="#{reservacionController.selected.idUsuario}" required="true" requiredMessage="#{bundle.EditReservacionRequiredMessage_idUsuario}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{usuarioController.itemsAvailableSelectOne}"
                                           var="idUsuarioItem"
                                           itemValue="#{idUsuarioItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{reservacionController.update}" value="#{bundle.Save}" update="display,:ReservacionListForm:datalist,:growl" oncomplete="handleSubmit(args, 'ReservacionEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ReservacionEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/reservacion/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListReservacionTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="ReservacionListForm">
                <p:panel header="#{bundle.ListReservacionTitle}">
                    <p:dataTable id="datalist" value="#{reservacionController.items}" var="item"
                                 selectionMode="single" selection="#{reservacionController.selected}"
                                 paginator="true"
                                 rowKey="#{item.idReservacion}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListReservacionTitle_idReservacion}"/>
                            </f:facet>
                            <h:outputText value="#{item.idReservacion}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListReservacionTitle_fechaReservacion}"/>
                            </f:facet>
                            <h:outputText value="#{item.fechaReservacion}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListReservacionTitle_fechaRecogerLibros}"/>
                            </f:facet>
                            <h:outputText value="#{item.fechaRecogerLibros}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListReservacionTitle_idUsuario}"/>
                            </f:facet>
                            <h:outputText value="#{item.idUsuario}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{reservacionController.prepareCreate}" update=":ReservacionCreateForm" oncomplete="PF('ReservacionCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":ReservacionViewForm" oncomplete="PF('ReservacionViewDialog').show()" disabled="#{empty reservacionController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":ReservacionEditForm" oncomplete="PF('ReservacionEditDialog').show()" disabled="#{empty reservacionController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{reservacionController.destroy}" update=":growl,datalist" disabled="#{empty reservacionController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/reservacion/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ReservacionViewDlg" widgetVar="ReservacionViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewReservacionTitle}">
            <h:form id="ReservacionViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{reservacionController.selected != null}">
                        <h:outputText value="#{bundle.ViewReservacionLabel_idReservacion}"/>
                        <h:outputText value="#{reservacionController.selected.idReservacion}" title="#{bundle.ViewReservacionTitle_idReservacion}"/>
                        <h:outputText value="#{bundle.ViewReservacionLabel_fechaReservacion}"/>
                        <h:outputText value="#{reservacionController.selected.fechaReservacion}" title="#{bundle.ViewReservacionTitle_fechaReservacion}">
                            <f:convertDateTime pattern="MM/dd/yyyy" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewReservacionLabel_fechaRecogerLibros}"/>
                        <h:outputText value="#{reservacionController.selected.fechaRecogerLibros}" title="#{bundle.ViewReservacionTitle_fechaRecogerLibros}">
                            <f:convertDateTime pattern="MM/dd/yyyy" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewReservacionLabel_idUsuario}"/>
                        <h:outputText value="#{reservacionController.selected.idUsuario}" title="#{bundle.ViewReservacionTitle_idUsuario}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="ReservacionViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>